num = int(input("Digite um número para a tabuada: "))
print("-" * 25)
print("{} vezes {:2} é igual a = {}".format(num,1,num*1))
print("{} vezes {:2} é igual a = {}".format(num,2,num*2))
print("{} vezes {:2} é igual a = {}".format(num,3,num*3))
print("{} vezes {:2} é igual a = {}".format(num,4,num*4))
print("{} vezes {:2} é igual a = {}".format(num,5,num*5))
print("{} vezes {:2} é igual a = {}".format(num,6,num*6))
print("{} vezes {:2} é igual a = {}".format(num,7,num*7))
print("{} vezes {:2} é igual a = {}".format(num,8,num*8))
print("{} vezes {:2} é igual a = {}".format(num,9,num*9))
print("{} vezes {:2} é igual a = {}".format(num,10,num*10))
print("-" * 25)
