algo = input("Digite algo: ")
print("É alfanumérico? ",algo.isalnum())	
print("É alfa? ",algo.isalpha())	
print("É formatação ASCII? ",algo.isascii())	
print("É decimal? ",algo.isdecimal())	
print("É dígito? ",algo.isdigit())	
print("É alphanuméric? ",algo.isidentifier())	
print("É minúsculo? ",algo.islower())	
print("É numérico? ",algo.isnumeric())	
print("É printável? ",algo.isprintable())	 
print("É espaço? ",algo.isspace())	 
print("Está capitalizada? ",algo.istitle())
print("É maiúsculo? ",algo.isupper())
